trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  PRISMA_API_URL: https://api0.prismacloud.io
  BC_SOURCE: vscode
  LOG_LEVEL: DEBUG

jobs:
- job: Prisma_Cloud_Job
  displayName: Prisma Cloud Job
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
    displayName: 'Use Python 3.8'
  - script: pip install checkov
    displayName: Install Checkov
  - script: checkov -d . --use-enforcement-rules --bc-api-key $(PRISMA_API_KEY) --repo-id prismaiac/bicepgoat --branch main
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: Run Checkov
